name: chat_boot_s1
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0-70.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.7.2
  flutter_bloc: ^9.0.0
  intl: ^0.20.2
  google_fonts: ^6.2.1
fonts:
  - family: ReemKufiInk
    fonts:
      - asset: fonts/ReemKufiInk-Regular.ttf
  - family: Zain
    fonts:
      - asset: fonts/Zain-Black.ttf
        weight: 900
      - asset: fonts/Zain-Bold.ttf
        weight: 700
      - asset: fonts/Zain-ExtraBold.ttf
        weight: 800
      - asset: fonts/Zain-ExtraLight.ttf
        weight: 200
      - asset: fonts/Zain-Italic.ttf
        style: italic
      - asset: fonts/Zain-Light.ttf
        weight: 300
      - asset: fonts/Zain-LightItalic.ttf
        style: italic
      - asset: fonts/Zain-Regular.ttf
        weight: 400

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
